const EventEmitter = require('events');

/**
 * Central EventBus for Eyes Care
 * Emits real-time state changes to Main process, System Tray,
 * Backend Terminal, Overlays, and Renderer windows.
 */
class EyesCareEventBus extends EventEmitter {
  constructor() {
    super();
    this.setMaxListeners(50);
  }

  // Common event constants
  static EVENTS = {
    DISPLAY_CHANGED: 'DISPLAY_CHANGED',
    BRIGHTNESS_CHANGED: 'BRIGHTNESS_CHANGED',
    TEMPERATURE_CHANGED: 'TEMPERATURE_CHANGED',
    PROFILE_CHANGED: 'PROFILE_CHANGED',

    DAY_MODE_STARTED: 'DAY_MODE_STARTED',
    NIGHT_MODE_STARTED: 'NIGHT_MODE_STARTED',

    SCHEDULE_STARTED: 'SCHEDULE_STARTED',
    SCHEDULE_COMPLETED: 'SCHEDULE_COMPLETED',

    BREAK_TICK: 'BREAK_TICK',
    BREAK_STARTED: 'BREAK_STARTED',
    BREAK_PAUSED: 'BREAK_PAUSED',
    BREAK_RESUMED: 'BREAK_RESUMED',
    BREAK_COMPLETED: 'BREAK_COMPLETED',
    BREAK_SKIPPED: 'BREAK_SKIPPED',

    USER_TIMER_TICK: 'USER_TIMER_TICK',
    USER_TIMER_STARTED: 'USER_TIMER_STARTED',
    USER_TIMER_PAUSED: 'USER_TIMER_PAUSED',
    USER_TIMER_RESUMED: 'USER_TIMER_RESUMED',
    USER_TIMER_COMPLETED: 'USER_TIMER_COMPLETED',

    APPLICATION_RULE_TRIGGERED: 'APPLICATION_RULE_TRIGGERED',
    FOCUS_CHANGED: 'FOCUS_CHANGED',
    MAGICX_CHANGED: 'MAGICX_CHANGED',

    MONITOR_CONNECTED: 'MONITOR_CONNECTED',
    MONITOR_DISCONNECTED: 'MONITOR_DISCONNECTED',

    SYSTEM_SLEEP: 'SYSTEM_SLEEP',
    SYSTEM_RESUME: 'SYSTEM_RESUME',

    BACKEND_STARTED: 'BACKEND_STARTED',
    BACKEND_STOPPED: 'BACKEND_STOPPED',
    BACKEND_RESTARTED: 'BACKEND_RESTARTED',

    LOG_ENTRY: 'LOG_ENTRY',
    STATUS_UPDATE: 'STATUS_UPDATE'
  };
}

module.exports = new EyesCareEventBus();
